# -*- coding: utf-8 -*-
"""codesoft_task_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bqf2FGwnblcqOm4XaM7Gc2rGjdv9F6fq
"""

# Step 1: Data Collection
import pandas as pd

# Assuming you have a dataset named 'advertising.csv'
sales_data = pd.read_csv('advertising.csv')

# Print the column names to inspect them
print(sales_data.columns)

# Continue with the rest of the code...


# Step 2: Data Preprocessing (if needed)
# Assuming preprocessing steps involve handling missing values, outliers, etc.
# (Code for preprocessing steps would be added here)

# Step 3: Feature Selection (if needed)
# Assuming feature selection techniques like correlation analysis or feature importance are used
# (Code for feature selection would be added here)

# Step 4: Model Selection
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Assuming Linear Regression is selected as the model
model = LinearRegression()

# Step 5: Model Training
# Check if 'sales' column exists in the dataset
if 'sales' in sales_data.columns:
    # 'sales' column is found, proceed with model training
    X = sales_data.drop(columns=['sales'])  # Features
    y = sales_data['sales']  # Target variable

    # Split the data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Train the model
    model.fit(X_train, y_train)

else:
    # 'sales' column is not found, print an error message
    print("Error: 'sales' column not found in the dataset.")

# Step 6: Model Evaluation (if needed)
# Assuming model evaluation is performed here (not shown in this code snippet)

# Step 7: Hyperparameter Tuning (if needed)
# Assuming hyperparameters are tuned using techniques like GridSearchCV or RandomizedSearchCV
# (Code for hyperparameter tuning would be added here)

# Step 8: Deployment (if needed)
# Assuming the trained model is deployed into production
# (Code for model deployment would be added here)